# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [1]:
a = [[2,2,3],
    [4 ,9,6],
    [7 ,8,5]]
  
b = [[9,8,2],
    [7,5,4],
    [3,6,1]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
for i in range(len(a)):
    for j in range(len(b)):
        result[i][j] = a[i][j] + b[i][j]

for r in result:
    print(r) 

[11, 10, 5]
[11, 14, 10]
[10, 14, 6]


### 2. Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np
a = [[2,2,3],
    [4 ,9,6],
    [7 ,8,5]]
  
b = [[9,8,2],
    [7,5,4],
    [3,6,1]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]
 
result = np.dot(a,b)

for r in result:
    print(r) 

[41 44 15]
[117 113  50]
[134 126  51]


### 3. Write a Python Program to Transpose a Matrix?

In [4]:
a=np.array([[1,2,6],
            [3,4,8],
            [1,2,3]])
a.transpose()

array([[1, 3, 1],
       [2, 4, 2],
       [6, 8, 3]])


### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [6]:
my_str = "This is Ineuron FSDA"

words=[word.lower() for word in my_str.split()]
words.sort()

print("The sorted words are: ")
for word in words:
    print(word)

The sorted words are: 
fsda
ineuron
is
this


### 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
punctuations='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = "Hello!! course is***fsda***"
no_punct=""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char
print(no_punct)    

Hello course isfsda
